### ISSUE TITLE
Globals are not auto-completed

### ISSUE THREAD

**Issue by mikesnoeren** [nystudio107/craft-autocomplete#8]
### Describe the bug
Globals are not auto-completed

### To reproduce
Steps to reproduce the behaviour:
1. Create a global (e.g. 'website')
2. Assign field to said global.
3. Try to use the autocomplete functionality

### Expected behaviour
The editor should auto-complete globals.

### Screenshots
Other auto-completions do work:
![craft autocompletes](https://user-images.githubusercontent.com/52166423/142217778-1b5fedd1-a027-4edc-ad68-40c651be0b62.png)
![entry autocompletes](https://user-images.githubusercontent.com/52166423/142218320-9154cd76-03ce-495a-b50c-ac6edbb50535.png)
Global auto-completion doesn't work:
![global in craft](https://user-images.githubusercontent.com/52166423/142218023-08cc479b-1292-4bd0-9ad7-bd28b9c7adf3.png)
![global does not autocomplete](https://user-images.githubusercontent.com/52166423/142219096-b95ba0a0-25cd-4d48-be50-93c8049cbeb3.png)

### Versions
- Plugin version: 1.0.5
- Craft version: 3.7.20

**Comment by khalwat** [comment]
Not experiencing that behavior here. It's possible you just need to regenerate the auto-complete classes, can you try deleting them from `storage/runtime/compiled_templates` and see if they regenerate with your globals in there as expected?

<img width="615" alt="Screen Shot 2021-11-17 at 11 20 27 AM" src="https://user-images.githubusercontent.com/7570798/142240469-40b148f1-2495-4cdb-941f-bd52834b1a61.png">

We might consider adding an event listener to invalidate the cache whenever:

- Globals are changed via `Globals::EVENT_AFTER_SAVE_GLOBAL_SET`

Globals being saved is one of the few things that will cause new variables to be introduced into Twig templates (that and installing new plugins).

cc: @bencroker

**Comment by khalwat** [comment]
So I was correct that we should add a listener to this event so that we invalidate the generated classes when a global set is saved, because they could be adding or renaming the injected globals.

However, globals still weren't showing up. It's because as of Craft CMS 3.7.8, Craft conditionally loads the `GlobalsExtension` only if it's a frontend request. So if the autocomplete classes are regenerated via a CP request (which is most likely), the globals won't be present.

Now we manually add the globals to the mix every time, which should take care of the issue.

Addressed in: https://github.com/nystudio107/craft-autocomplete/commit/0a2169e2bd22a607f334e46d8a08b0bf6645ca9d

Released as Craft Autocomplete 1.0.6 -> https://github.com/nystudio107/craft-autocomplete/releases/tag/1.0.6

**Comment by bencroker** [comment]
Very cool!

**Comment by mikesnoeren** [comment]
Very cool indeed. Thanks for the release!
